language: java
jdk:
- openjdk8
sudo: required
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.9.0
addons:
  sauce_connect: true
before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
install:
- bash scripts/install.sh
- bash scripts/build.sh rmspogfo
- cp target/rmspogfo.war docker/pogues-bo/
before_script:
- sudo sysctl -w vm.max_map_count=262144
- pushd docker
- docker-compose up -d --build
- popd
script:
- mvn test
- bash scripts/coveralls.sh
- mvn failsafe:integration-test
- bash scripts/e2e.sh
after_success:
- bash scripts/tag.sh
deploy:
  provider: releases
  api_key:
    secure: p7vVj36CMfn1gdoV4XUyx3Vb45x8KV0OqTh2TpjcPLXIxuW3SPKMFszhIRSXtgScz6GpAbFUhJFEj//DJtRyPSeirnDoc5TR49FgZVj5f64II9M1M1fiEto+bktv3MFQ97MAotTre4ac59+3fNLNGsc38H22EyUxLS6LBDQ8eUzgeBu92sefbH1zClDri/RAeyZLuT6daGGPGAQWywAHjz7NI9xw2pJQ27eWCRCh64VBOsDiTq+J9FzenUnbHcJY/ZIVtddR2ERFG/uNd4bLM938YVvT3qrE9HC2nLcyMw9ZqwqM/uH7m2ljWH2SlI03Ed9HWfQ+I44tLYF2EQyPY7nlh97ottyCslfB41QvokTqwrF2IiXhVyzC0kKtSYsmw9x8sh7ee1G26z9qr5oL8LFd9572fYvYaRkP7JlUtk2JbCp7IToC3o25BJRuv2pao8BQLH4Vb6heELWuoiVi+iQ0yJFkB6dASNejdiKGjsr43Yy66yOP9lWTTEYmbaVDLMHQRJ10R6omSVdYR3xveKeCF+i+nfQaBWvIcHngIzsCWguD7mzItgYQ2VnEzV8Mxy3BKTKbPOIClJGzGwitZycxU6TTKBzMwJouW18Qbw5Pr+tyrTCF7wtoAlTy/MCVYefYKiP364X3YBHyqg93MZkEIal0iPGdjSwSOOy8kwU=
  file: target/rmspogfo.war
  skip_cleanup: true
  on:
    repo: InseeFr/Pogues-Back-Office
    branch: zenika-dev
    condition: -f "$TRAVIS_BUILD_DIR/.tag" && $(cat "$TRAVIS_BUILD_DIR/.tag") =~ v[0-9]\.[0-9]\.[0-9].*
    tags: false
#deploy:
#  provider: releases
#  api_key:
#    secure: bTtVeXMcjr5v6SKE09H7Rq5ca8KIpi2LmduC9O4b8ZnrK4Xsymhk8+QSfPOq6oQ83JWv4j+TPokcHRw03UatDVwifjumSFeV41D2IicXsF8gUo5Hem49u3dVVSTojQm7ei7ViD34Lf7oyYaTKJlXDqWbNgxrMwhBFFqJF/p5N+F3gGaek+B5cNcco5QfMlxPmLqk8vfkaUAeCQw6EU4fJ/hwz1dJpv3+Rq2ZnpHGrToOByOysrxO3XqkldtEh02CY8JXoTWxKQss4l78RQ3TI2PpIQD0YSm97+bBQWuPPFS89iOvuJaFdZ210nBSTL3VVagynQliRTj2JzNr3MBV72wx2xUqtxrfymicpuYW4qkaR5KRkJ+x3giIdu917fN/1+E08KfeAy4TeQdjLMrFP5j/kLcAR7NWubYKwUOGf7fTimeifx7qcCVpkaxaMiDKAZiqdaBOt+ciUYsCftm6Bu8wlb/P0t2/Dno3437GD8xgBapTMd7SJAwPp3ktQXKc/Y4x3ZOVY95T6D3yZcqidGFqXlbZf83eu/5McHnscvocHUszNZx0tu8B/eoC4B6E+UxcgH367AYMkeG/Fxw3AMlP/kaUl9NDiSj6SwstXr4LKNbgbERZ7vvQ2gq/zH4yWcw2lhmsX9WoSllQzjtHsacA9y+TBHJWWK6DjjE6ek8=
#  file: target/rmspogfo.war
#  skip_cleanup: true
#  on:
#    repo: Zenika/Pogues-Back-Office
#    branch: zenika-dev
#    condition: -f "$TRAVIS_BUILD_DIR/.tag" && $(cat "$TRAVIS_BUILD_DIR/.tag") =~ v[0-9]\.[0-9]\.[0-9].*
#    tags: false
after_deploy:
- bash scripts/gitbook.sh
branches:
  except:
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*/"
