name: Pogues Back Office Docker CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout Lunatic-Model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Lunatic-Model
          path: Lunatic-Model
      - name: Build Lunatic-Model with Maven
        working-directory: ./Lunatic-Model
        run: mvn clean generate-sources install -DskipTests
      - name: Checkout Pogues-Model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: main
          repository: InseeFr/Pogues-Model
          path: Pogues-Model
      - name: Build with Maven Pogues-Model
        working-directory: ./Pogues-Model
        run: mvn clean generate-sources install -DskipTests
      - name: Test, package and analyze with maven & SonarCloud
        run: mvn verify sonar:sonar -Dsonar.projectKey=InseeFr_Pogues-Back-Office -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Checkout Lunatic-Model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: master
          repository: InseeFr/Lunatic-Model
          path: Lunatic-Model

      - name: Build Lunatic-Model with Maven
        working-directory: ./Lunatic-Model
        run: mvn clean generate-sources install -DskipTests

      - name: Checkout Pogues-Model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: main
          repository: InseeFr/Pogues-Model
          path: Pogues-Model

      - name: Build with Maven Pogues-Model
        working-directory: ./Pogues-Model
        run: mvn clean generate-sources install -DskipTests

      - name: Checkout Pogues-Back-Office repo
        uses: actions/checkout@v2

      - name: Build with Maven Pogues-Back-Office
        run: mvn clean package -DskipTests -B -V --file pom.xml

      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/*.war
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: war
          path: target/
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.8.4
        with:
          images: inseefr/pogues-back-office # list of Docker images to use as base name for tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/master' && 'inseefr/pogues-back-office:latest' || '' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
