name: Pogues docs publication
on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@master
        with:
          source_dir: docs
          token: ${{ secrets.GITHUB_TOKEN }}
