name: Pogues Back Office release on tag

on:
  push:
    tags:
      - "*.*.*"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Test, package and analyze with maven & SonarCloud
        run: mvn --no-transfer-progress verify sonar:sonar -Dsonar.projectKey=InseeFr_Pogues-Back-Office -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven Pogues-Back-Office
        run: mvn clean package -DskipTests -B -V --file pom.xml --no-transfer-progress

      - name: Upload war
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar

  build-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build
        id: download
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: target/

      - name: Get current version
        id: version
        run: echo "prop=$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.version.outputs.prop }}
          files: target/pogues-bo.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
