name: Pogues Back Office release on tag

on:
  push:
    tags:
      - "*.*.*"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test, package and analyze with maven & SonarCloud
        run: mvn --no-transfer-progress verify sonar:sonar -Dsonar.projectKey=InseeFr_Pogues-Back-Office -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven Pogues-Back-Office
        run: mvn clean package -DskipTests -B -V --file pom.xml

      - name: Upload war
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar

  build-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build
        id: download
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: target/

      # Todo: add automated changelog step (based conventional commit using requarks/changelog-action)

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          target_commitish: ${{ github.head_ref || github.ref }}
          name: "v${{ needs.check-version.outputs.release-version }}"
          #body: see todo
          files: target/pogues-bo.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
