name: Pogues Back Office tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore: ['docs/**', 'scripts/**', 'Dockerfile', 'LICENSE', 'CHANGELOG.md', 'README.md']

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests with Maven
        run: mvn clean test --no-transfer-progress
